### ISSUE TITLE
Copyright header needs to be updated.

### ISSUE THREAD

**Issue by leogtzr** [fasseg/exp4j#102]
```
* Copyright 2014 Frank Asseg
```

**Comment by shuvamc019** [comment]
I don't know much about copyright law, but based on internet research, the general consensus is that copyright on source code should be the year that the copyright was obtained or the year that the product was first released.  Therefore, I think that leaving it as 2014 is fine.

**Comment by leogtzr** [comment]
@fasseg  thoughts?
