### ISSUE TITLE
Feature request  to be able to set the equation on an existing instance of ExpressionBuilder

### ISSUE THREAD

**Issue by vandanagopal** [fasseg/exp4j#25]
In our application we evaluate lots of equations every second. It seems quite costly to have to create a new instance of ExpressionBuilder, set all the variables and functions for every equation.
It would be great if there could be a setter on ExpressionBuilder using which I could set the equation string on an existing instance of ExpressionBuilder.

**Comment by fasseg** [comment]
So you want to reuse the ExpressionBuilder for a different equation?

For Example:

```Java
ExpressionBuilder builder = new ExpressionBuilder("sin(x)")
    .variable("x", 2)

double res1 = builder.build().evaluate();
builder.expression("cos(x)")
double res2 = builder.build().evaluate();
```

Is this correct?

**Comment by vandanagopal** [comment]
Yes, that is exactly correct. I don't want to have to set all the functions
and variable names again.
Greatly appreciate you looking into this.

**Comment by fasseg** [comment]
@vandanagopal 
I dont think that setting the expression on a current `ExpressionBuilder` is the way to go after looking at the code. The expression is currently final in the ExpressionBuilder, which gives you free thread-safety for expression builders when handled correctly and I don't want to lose that.
So my suggestion is either have some kind of `copyOf()` method on the ExpressionBuilder which accepts a new expression and copies function and variables from an existing one:
```Java
ExpressionBuilder builder = new ExpressionBuilder("sin(x)")
    .variable("x", 2);

double res1 = builder.build().evaluate();
ExpressionBuilder derived = builder.copy("cos(x)")); //  Calling copy creates a new instance
double res2 = derived.build().evaluate();
```

or having the Constructor accept a List of functions and a Set of variable names:
```Java
ExpressionBuilder b = new ExpressionBuilder("sin(x)")
    .variable("x", 2);
double res1 = b.build().evaluate();
ExpressionBuilder derived = new ExpressionBuilder("sin(x)", b.getFunctions(), b.getVariables());
double res2 = derived.build().evaluate();
```

What do you guys think?

**Comment by leogtzr** [comment]
@fasseg Looks good! I like the overloaded constructor idea! :)

**Comment by fasseg** [comment]
@vandanagopal: Would such an overloaded Constructor satisfy your use-case?
I could add this to the next release.

**Comment by vandanagopal** [comment]
Yes I like the overloaded constructor idea too - that would be great.
Thanks.

**Comment by fasseg** [comment]
The following PR has been merged to master and will give you an easy way to copy expressions in the next release:
https://github.com/fasseg/exp4j/pull/43
