### ISSUE TITLE
Inconsistency in Function.isValidFunctionName()

### ISSUE THREAD

**Issue by dktcoding** [fasseg/exp4j#27]
There's an inconsistency between ```Function.getAllowedFunctionCharacters()``` and ```Function.isValidFunctionName()```, the first returns only english ASCII letters, but the later uses ```Character.isLetter()``` which accepts symbols that represent letters in every other [language](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#isLetter(char)), so for instance (assuming that the accepted characters should be the ones expressed in ```Function.getAllowedFunctionCharacters()```):

* ```Function.isValidFunctionName("logñ")``` should return ```false``` but it returns ```true```
* ```Function.isValidFunctionName("üla")``` should return ```false``` but it returns ```true```
* etc...

The same goes for the use of ```Character.isDigit()```.

**Comment by dktcoding** [comment]
Thinking about backwards compatibility, perhaps it would be better to deprecate ```Function.getAllowedFunctionCharacters()``` and keep using ```Character.isLetter()``` and ```Character.isDigit()```, that way there's less chance to break currently working applications.

**Comment by fasseg** [comment]
Right. This is a regression from when I implemented https://github.com/fasseg/exp4j/issues/19, which allowed unicode chars to be used in vars and functions.
 I will fix this asap and roll a new release.

Thanks for the report!

**Comment by fasseg** [comment]
Fixed via deprecation in 0.4.5
