### ISSUE TITLE
Ability to solve for a varaible

### ISSUE THREAD

**Issue by tburch** [fasseg/exp4j#45]
Maybe I missed this, but I don't see a way to solve for a variable. Is there a way to do that? I'd like to be able to do something like this:
```
double x = new ExpressionBuilder("(4*x)+2=2*(x+6)").build().solveFor("x");
Assert.assertEquals(5, x, 0.0);
```

**Comment by fasseg** [comment]
Hey @tburch, 

Sorry but exp4j is just an expression evaluator not a function solver. It's not only out of scope for the project, but also the algorithm used (Shunting Yard) is not able to solve general functions.

**Comment by tburch** [comment]
Thanks @fasseg!

**Comment by tburch** [comment]
@fasseg I was thinking about this a little more. Isn't this really just the same as expression evaluation? Essentially, this is just rearranging the equation and then doing the expression evaluation, no?

**Comment by fasseg** [comment]
@tburch: In Simple cases this migth be true. So e.g. solving 1-x=0 might be trivial, but solving something more intricate like x(1-4)=3 or some higher order polynomial is much harder and involves a lot of logic which is not trivial at all.
