### ISSUE TITLE
Support for variable assignment

### ISSUE THREAD

**Issue by andrewv99** [fasseg/exp4j#46]
Hi,

Without wanting to ask for statements to be introduced into the language, I was wanting to be able to chain a number of assignment expressions together, simulating separate assignment statements, and both store and later reference intermediate assigned results within the expression evaluation. For example, assume the variable map is set up with:

a = 2
b = 3

Then:

"(c = a + 2) +
(d = c*3 + b) +
(b = d + 2*b)"

and assuming the exp4j expression evaluation rules, would yield a map with:
a = 2
b = 21
c = 4
d = 15

b has been updated. c and d have been added/set.

If the total addition expression were likely to result in a double overflow, the intermediate expressions could be multiplied by zero, thus avoiding that possibility - this would be ok for me because the overall expression value is unimportant for my purposes.

This would be good enough for what I wanted to do. The assignment operations would update the variable map. Is there any plan to do something like this, or if not, could anyone provide some pointers on  how best to modify the code to support this ?

Thanks
Andrew

**Comment by fasseg** [comment]
Sorry Andrew,
but IMHO this is out of scope for exp4j. Exp4j is a pure expression evaluator that returns a single double result.
