### ISSUE TITLE
Allow not predefining (all) variables and lazy-computing variable values

### ISSUE THREAD

**Issue by hallvard** [fasseg/exp4j#57]
I'm working on an application where the number of allowed variables is potentially very large, so to add them all with their values is costly. Instead, it would be better to 1) collect the used variable names in ExpressionBuilder and 2) be able to iterate through them and set the values of those actually used.
I propose a flag in ExpressionBuilder that controls how tokens that look like variables are handled. If the mode is "allow undefined variables", variable-like tokens that are unknown as either defined variables or functions, are automatically added as variables. Before the evaluate method needs the values, they should of course be set or an exception should be thrown.

**Comment by fasseg** [comment]
Im not sure I understand you correctly. You do not have to set the variable values in the ExpressionBuilder. Supplying the names of the variables using:

[ExpressionBuilder.variables(Set\<String\> variables)](https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/ExpressionBuilder.java#L88)
[ExpressionBuilder.variables(String ... variables)](https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/ExpressionBuilder.java#L93) 
[ExpressionBuilder.variable(String variable](https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/ExpressionBuilder.java#L98)

is enough. You can later set the variable values using

[Expression.setVariable(String name, double value)](https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/Expression.java#L67)

So this would be possible:
```Java
final ExpressionBuilder b =  new ExpressionBuilder(x+y)
    .variables("x", "y");
final Expression e = b.build();
e.setVariable("x", 1.5d);
e.setVariable("y", 2.3d);
double result = e.evaluate();
```

I strongly suspect that I did not understand you completely, so please elaborate a bit. If possible with Pseudocode examples....

**Comment by hallvard** [comment]
Instead of using b.variables(...) before b.build() I would like the ExpressionBuilder to accept all variables and then provide a means for iterating through the variables that are actually used and set their values before e.evaluate. The use case is a data collection application where an expression may refer to any of a very large set of values, each with a unique name. However, adding each of them in advance with b.variable(...) requires me to iterate through all potential variables, only a few of which will be used. If I instead could use **for (String varName : b.getUndefinedVariables()) { e.setVariable(varName, getActualVarValue(varName)); }** I would save a lot of time and space.

**Comment by fasseg** [comment]
Hey hallvard, 
Sorry for taking so long to response. Your suggested change is not possible without creating a new method on ExpressionBuilder, e.g. buildLazy(), since we cannot break existing clients by introducing API changes, also refactoring of Expression handling and the Tokenizer would have to be done. So this feature will most likely not be implemented in the near future, but I have it on my list of suggested features for exp4j.

Have Fun!

FRANK

**Comment by hallvard** [comment]
Fair enough. I am willing to invest some time adjusting my (working) implementation, if you can be precise on the kind of changes that are (not) acceptable. If I understand you correctly, I should not 1) change existing API and 2) introduce as few new methods and classes as possible? What about introducing new subclasses?

**Comment by sarxos** [comment]
Hi @hallvard,

I had similar issue where I had to extract functions and variables that are used in expression but has not been defined by ```ExpressionBuilder::variables(String... vars)```. I'm not sure if this will satisfy your needs since it was on a much smaller scale (only few variables) so I was not bothered by a performance.

The code below will set only these variables which are used in expression:

```java
Set<String> variables = new LinkedHashSet<>();
Expression exp = null;
ExpressionBuilder builder = new ExpressionBuilder("3 * sin(pi) - x + 2 / (y - 2) + z + p(1)");

do {
	try {
		exp = builder.build();
		break;
	} catch (UnknownFunctionOrVariableException e) {
		builder.variable(e.getToken());
		variables.add(e.getToken());
	}
} while (true);

// set values for the variables used in expression

for (String variable : variables) {
	exp.setVariable(variable, getValue(variable));
}

double value = exp.evaluate();
```

**Comment by hallvard** [comment]
@sarxos Nice trick! The performance here depends on the complexity of the expression, not on the number of possible variables (which in my case can be very large). In my case, the same expression is evaluated many times along the time axis, but I need only find the set of variables once, so the performance shouldn't suffer. Thanks!
