### ISSUE TITLE
Possible Improper Boolean operators

### ISSUE THREAD

**Issue by Duke02** [fasseg/exp4j#67]
In Expression.java in the main src package [https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/Expression.java](url) , there is a function called "checkVariableName(String name)" In here, it checks if the instance's custom functions contains the given name OR if the builtin functions contains the given name, then throws an error if the result evaluates to true saying that the variable cannot be a built in variable.

Shouldn't rather be the && operator as it must not be in both user functions AND the builtin functions?

**Comment by fasseg** [comment]
Hmm I gather you talk about this:
```Java
    private void checkVariableName(String name) {
        if (this.userFunctionNames.contains(name) || Functions.getBuiltinFunction(name) != null) {
            throw new IllegalArgumentException("The variable name '" + name + "' is invalid. Since there exists a function with the same name");
        }
    }
```
This throws an error if the name is used in the builtin functions __or__ the user functions, so it can not be used in either, which seems right to me.
