### ISSUE TITLE
sin90-sin90 doesnt give an output of 0

### ISSUE THREAD

**Issue by a35joshi** [fasseg/exp4j#71]
When I do a sin90-sin90 I get 0.909220...
When I do a sin90 then press equal to and then do -sin90 I get a 0 (which is correct)
Same for (sin90/sin90). Doesn't give 1. 
UPDATE : Placing brackets around them solves the issue like (sin90)-(sin90) is 0. But can we also have sin90-sin90 display 0?

Am I missing something here?

Thank You!
Anurag

**Comment by dktcoding** [comment]
Hi there

I honestly can't understand the expression you are using... I'm assuming is `sin(90)/sin(90)`? that should evaluate to `1`, if you are actually calling a function without the parentheses the result will be fairly complicated to anticipate, in that case you'll have `sin90/sin90` which will be tokenized as `90 90 sin / sin` and roughly translates to `sin(90/sin(90))~=0.14`.

Almost the same goes for `sin90-sin90`.

Regards

**Comment by a35joshi** [comment]
Alright. That was the clarification I needed. Thank You!
