### ISSUE TITLE
using angle function and pi

### ISSUE THREAD

**Issue by swalesch** [fasseg/exp4j#76]
**Problem**
You all know 
sin(pi) = 0
cos(pi/2) = 0
tan(pi/4) = 1

I know it is a rounding problem but the result will be only close to the values above. That could lead to problems in calculations.

Real output right now:
sin(pi) = 122..E-16
cos(pi/2) = 6.12...E-17
tan(pi/4) = 0.999999

**Possible solution:**
Add a rounding option to the build ExpressionBuilder for angle functions. So i can say round the result of  sin/cos/tan to a given numbers after the comma.

**Comment by dktcoding** [comment]
As a matter of fact `sin(pi)` is calculating exactly `Math.sin(Math.PI)` which is what the IEEE 754 (and therefore Java) specify as output. 

The thing is: `exp4j` is used in numerical calculations, so changing the output (like rounding) to accommodate the result to a "politically correct" value can be very damaging (results need to be reproducible). 

There are several options to show the "expected" results (you should use them regardless of `exp4j` when displaying floats):
- wrap the expression in a `round(...)`
- use `String.format("%5.2f", exp.evaluate()) //Or the combination you prefer`
- use [`NumberFormatter`](https://docs.oracle.com/javase/7/docs/api/javax/swing/text/NumberFormatter.html)
- round the value to the number of digits you consider good enough like:
 `Math.round(num * 100) / 100. //<-2 decimal places rounding`

Regards!

**Comment by fasseg** [comment]
@swalesch:

Since these rounding errors are due to the floating point representation in the memory I do feel reluctant to add this as a feature. But it is certainly possible to add your own trigonometric function to exp4j using the custom function feature.
Something like this should work:
```
        Expression e = new ExpressionBuilder(("rndsin(pi, 5)"))
                .function(new Function("rndsin", 2) {
                    @Override
                    public double apply(double... args) {
                        double scale=Math.pow(10,args[1]);
                        return Math.round(Math.sin(args[0]) * scale) / scale;
                    }
                })
                .build();
        System.out.printf("Result: %f", e.evaluate());
```

Hope this helps, 

Frank

**Comment by swalesch** [comment]
oh well i did not see that option, of cause that will solve the problem!
so i will just overwrite the function for sin/cos/tan ... that worked for me
thanks! You can close this issue
