### ISSUE TITLE
exp4j considers the following expression valid "[A+B)"

### ISSUE THREAD

**Issue by kalypzo** [fasseg/exp4j#78]
## How to reproduce
Perform the following code in java:

```java
Expression e = new ExpressionBuilder("[A+B)").variable("A").variable("B").build();
ValidationResult res = e.validate(false);
assertFalse(res.isValid())
```

## Actual Result
Test code fails

## Expected Result
Test code pass

## Additional Notes
I believe having a mathematical expression in such form would be incorrect, but maybe there's something I'm unaware of.

**Comment by fasseg** [comment]
Hey @kalypzo, 
Thanks for the issue report. Currently all brackets are treated the same way in validation and a simple counter is used for checking the number of open brackets against the number of closed ones. It should be fairly straight forward to adapt the tokenizer to and  validation to use different types and counters for different brackets.

**Comment by kalypzo** [comment]
Ah, I see, thanks for the info.
I ended up just using my own validation before passing to the exp4j library to get around this.
