### ISSUE TITLE
Need some more operators

### ISSUE THREAD

**Issue by trans** [fasseg/exp4j#93]
Wanted to add operators for Unicode chars `×` and `÷` but of course get IllegalArgumentException because of

    public static final char[] ALLOWED_OPERATOR_CHARS = { '+', '-', '*', '/', '%', '^', '!', '#','§', '$', '&', ';', ':', '~', '<', '>', '|', '='};

I can think of a few other Unicode characters that are obvious adds too, e.g. `√`, `∛`, `⌈`, `⌊`, etc. Please consider adding some of these [other characters](http://xahlee.info/comp/unicode_math_operators.html) and really [all of these](http://xahlee.info/comp/unicode_APL_symbols.html) could be valid.

In the mean time I am trying to figure out the simplest way to go about adding `×` and `÷` as I have to have at least those for my application.

Thanks for this library btw!

**Comment by mohamed2a** [comment]
Hi, I think this PR will never be approved, apparently, the owner has stopped code maintenance.
I propose that we work together on my forked repository

Best regards

**Comment by fasseg** [comment]
Indeed I do not have the time anymore to maintain exp4j and I'm currently looking for someone to take over from me. So please let me know if you're interested in maintaining exp4j.

Have fun!

Frank

**Comment by subramaniant** [comment]
Hi Frank,

I am happy to work on your exp4j . It is really good API and need to be maintain and i have added request for '÷' char . 

Here is changes 

Operator.java
 public static final char[] ALLOWED_OPERATOR_CHARS = { '+', '-', '*', '/', '%', '^', '!', '#','§', '$', '&', ';', ':', '~', '<', '>', '|', '=','÷'};

Operators.java 

Operators.getBuiltinOperator() {
...
            case '/':
            case '÷':
                return builtinOperators[INDEX_DIVISION];
..

Let me know your view and happy to work with you..
